CREATE TABLE motorista (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    cnh VARCHAR(20) NOT NULL UNIQUE,
    telefone VARCHAR(20),
    email VARCHAR(100),
    disponibilidade ENUM('DISPONIVEL', 'EM_ATENDIMENTO', 'INDISPONIVEL') NOT NULL DEFAULT 'DISPONIVEL'
);
